categories_list:
    path: /{page}
    defaults: { _controller: App\Controller\CategoryController::listAction, page: 1 }
    requirements:
        page: \d+
        
categories_create:
    path: /create
    defaults: { _controller: App\Controller\CategoryController::createAction }
    
categories_edit:
    path: /edit/{id}
    defaults: { _controller: App\Controller\CategoryController::updateAction }
    requirements:
        id: \d+
        
categories_delete:
    path: /delete/{id}
    defaults: { _controller: App\Controller\CategoryController::deleteAction }
    requirements:
        id: \d+