issues_create:
    path: /projects/{identifier}/issues/create
    defaults: { _controller: App\Controller\IssueController::createAction }
    
issues_list:
    path: /projects/{identifier}/issues/{page}
    defaults: { _controller: App\Controller\IssueController::listAction, page: 1 }
    
issues_edit:
    path: /issues/{id}
    defaults: { _controller: App\Controller\IssueController::updateAction }
    requirements:
        id: \d+
        
issues_ajax_update:
    path: /issues/ajax/update
    defaults: { _controller: App\Controller\IssueController::ajaxUpdateAction }
    methods: [POST]