homepage:
    path: /
    defaults: { _controller: App\Controller\HomeController::indexAction }
    
backend_auth:
    path: /auth
    defaults: { _controller: App\Controller\SecurityController::authAction }

projects:
    resource: "projects.yml"
    prefix: /projects
    
trackers:
    resource: "trackers.yml"
    prefix: /trackers
    
priorities:
    resource: "priorities.yml"
    prefix: /priorities
    
issue_status:
    resource: "issue_status.yml"
    prefix: /statuses
    
roles:
    resource: "roles.yml"
    prefix: /roles
    
users:
    resource: "users.yml"
    prefix: /users
    
issues:
    resource: "issues.yml"
    
categories:
    resource: "categories.yml"
    prefix: /categories