roles_list:
    path: /{page}
    defaults: { _controller: Tracker\Controller\RoleController::listAction, page: 1 }
    requirements:
        page: \d+
        
roles_create:
    path: /create
    defaults: { _controller: Tracker\Controller\RoleController::createAction }
    
roles_edit:
    path: /edit/{id}
    defaults: { _controller: Tracker\Controller\RoleController::updateAction }
    requirements:
        id: \d+
        
roles_delete:
    path: /delete/{id}
    defaults: { _controller: Tracker\Controller\RoleController::deleteAction }
    requirements:
        id: \d+